apiVersion: apps/v1
kind: Deployment
metadata:
  name: gradle-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gradle-app
  template:
    metadata:
      labels:
        app: gradle-app

    spec:
      serviceAccountName: shohag-build-bot
      containers:
        - name: gradle-app
          image: shohagbkash/tekton-gradle-test:latest
          ports:
            - containerPort: 9090
